---
title: "hw1"
---

https://github.com/josh-jackson/alda24/tree/main/homework%20data

Answer the questions below using the HW2 dataset from github [here](https://github.com/josh-jackson/alda24/tree/main/homework%20data)

There are 7 waves of data, each with a different file (hw2-t1, hw2-t2, etc). There are five different types of repeated measures variables, all from "the Big Five" of personality. Each of these five constructs have 9 items associated with them. See hw-2 codebook for basic details.

To answer the questions below you will need to do a number of initial steps (bring data sets into R, create composites and reverse code so the variables are scored in the correct direction). You may create a codebook by modifying the existing one or by doing it all in R -- it is your choice.

1.  How many observations are there? How many subjects? How many subjects have more than 3 observations? Create a nice table to answer these questions.

2.  Run a simple growth model with a random slope for the extraversion composite.

    a\. Describe why you coded time in the manner that you did.

    b\. Interpret each coefficient, including the random effects and correlation between the slope and the intercept.

    c\. Create a figure that represents the average or fixed effect trajectory and then individual trajectories.

    d\. Create a figure that represents that amount of variation in the slope.

3.  Defines the intercept as the final time point. How does this differ form the previous model -- what is the same/different?

4.  Should the extraversion random slope be included or should slope be fixed?
